/*
 * strings.js — GENERATED by tools/build_i18n.js. DO NOT EDIT BY HAND.
 *
 * Runtime translation table backing the manual language switch in
 * Settings. The static UI binds to src/i18n/*.json via $t() and follows
 * the device language automatically; this module exists for the cases
 * where the user has chosen a language that differs from the system one.
 *
 * Usage:
 *   import { tr, setLang, resolveLang } from '../../common/js/strings.js';
 *   tr('settings.autoCenter')        -> the string in the active language
 *   setLang('zh' | 'en' | 'system')  -> apply an override
 */

export const LANG_ZH = 'zh';
export const LANG_EN = 'en';

/* Active language. Starts as the device language and is replaced once
 * storage has been read (or the user picks one in Settings). */
let _lang = LANG_EN;

/* The device language, resolved once at startup from
 * configuration.getLocale(). Used as the target of the 'system' mode. */
let _systemLang = LANG_EN;

/* The user-facing preference: 'system' | 'zh' | 'en'. Kept separate from
 * _lang so that a locale change reported by the system does NOT silently
 * override an explicit choice the user made in Settings. */
let _mode = 'system';

/*
 * Record the device language and, if the user is following the system,
 * switch to it. Called on every page show and on configuration change.
 * Never clobbers an explicit zh/en override.
 */
export function setSystemLang(l) {
  _systemLang = (l === LANG_ZH) ? LANG_ZH : LANG_EN;
  if (_mode === 'system') _lang = _systemLang;
}

export function systemLang() { return _systemLang; }

export function setLang(mode) {
  if (mode === 'zh' || mode === LANG_ZH) { _mode = LANG_ZH; _lang = LANG_ZH; return; }
  if (mode === 'en' || mode === LANG_EN) { _mode = LANG_EN; _lang = LANG_EN; return; }
  /* anything else = follow the system */
  _mode = 'system';
  _lang = _systemLang;
}

export function getLang() { return _lang; }

export function getMode() { return _mode; }

/*
 * Resolve the language that should actually be used, given the stored
 * preference and the device locale. 'system' is the default.
 */
export function resolveLang(pref, deviceLang) {
  const dev = (deviceLang === LANG_ZH) ? LANG_ZH : LANG_EN;
  if (pref === LANG_ZH || pref === LANG_EN) return pref;
  return dev;
}

const TABLE = {
  zh: {
    "app.name": "Chess",
    "app.continueGame": "继续对局",
    "app.startGame": "开始游戏",
    "app.settings": "下棋设置",
    "app.about": "关于",
    "app.exitApp": "退出应用",
    "app.done": "完成",
    "setup.step1Title": "选择对局模式",
    "setup.step2Title": "用时设置",
    "setup.modeTwo": "双人对弈",
    "setup.modeTwoDesc": "两人轮流走子",
    "setup.modeAi": "人机对战",
    "setup.modeAiDesc": "与内置 AI 对弈",
    "setup.sideLabel": "我执",
    "setup.sideWhite": "白方",
    "setup.sideBlack": "黑方",
    "setup.minutesLabel": "每方时长",
    "setup.minutesUnit": "分钟",
    "setup.minutesInf": "无限制",
    "setup.incrementLabel": "每步加秒",
    "setup.incrementUnit": "秒",
    "setup.levelLabel": "AI 难度",
    "setup.levelEasy": "简单",
    "setup.levelNormal": "普通",
    "setup.levelHard": "困难",
    "setup.levelMaster": "大师",
    "setup.levelEasyShort": "简单",
    "setup.levelNormalShort": "普通",
    "setup.levelHardShort": "困难",
    "setup.levelMasterShort": "大师",
    "setup.next": "下一步",
    "setup.start": "开始下棋",
    "settings.title": "下棋设置",
    "settings.autoCenter": "选中后自动居中",
    "settings.boardSize": "棋盘大小",
    "settings.boardStandard": "标准",
    "settings.boardLarge": "放大",
    "settings.boardCompact": "紧凑",
    "settings.language": "语言",
    "settings.langSystem": "跟随系统",
    "settings.langChinese": "中文",
    "settings.langEnglish": "English",
    "settings.on": "开启",
    "settings.off": "关闭",
    "game.white": "白",
    "game.black": "黑",
    "game.undo": "悔棋",
    "game.menu": "菜单",
    "game.menuTitle": "棋局菜单",
    "game.endGame": "结束对局",
    "game.resign": "认输",
    "game.draw": "和棋",
    "game.exitGame": "退出对局",
    "game.continueGame": "继续对局",
    "game.playAgain": "再来一局",
    "game.viewGame": "查看棋局",
    "game.autoCenterOn": "自动居中",
    "game.boardSizeLabel": "棋盘大小",
    "game.playVsAi": "人机对弈",
    "game.aiLevelLabel": "AI 难度",
    "game.hintTap": "点击棋子开始走子",
    "game.gameOver": "对局结束",
    "game.whiteTurn": "白方回合",
    "game.blackTurn": "黑方回合",
    "game.noUndo": "还没有可以悔的棋",
    "game.undoDone": "已悔棋",
    "game.thinking": "请稍候",
    "game.aiCantMove": "无法走子",
    "game.boardError": "局面异常",
    "game.resignAsk": "对手认输",
    "game.youWhite": "你执白棋",
    "game.youBlack": "你执黑棋",
    "game.whiteFirst": "执白先行",
    "game.drawAgreed": "双方同意",
    "game.stalemate": "逼和",
    "game.checkmate": "将死",
    "game.timeout": "超时",
    "game.wins": "胜",
    "game.settingsTitle": "下棋设置",
    "game.closeSettings": "完成",
    "game.on": "开",
    "game.off": "关",
    "game.aiTurn": "AI 回合，请稍候",
    "game.aiWhiteFirst": "AI 执白先行",
    "game.switchedTwo": "已切换为双人对弈",
    "game.selectHint": "请先选择当前回合的棋子",
    "game.moveDone": "走子完成，请交给",
    "game.checkPass": "将军，请交给",
    "game.reselect": "已选择 ",
    "game.tapBlueDot": "，点击蓝点落子",
    "game.restoredTurn": "已恢复对局，轮到",
    "game.selectedTurn": "的回合",
    "game.gameOverHint": "对局已结束",
    "game.drawShort": "和棋",
    "game.resignWins": "胜（对手认输）",
    "game.timeoutWins": "胜（超时）",
    "game.mateWins": "胜（将死）",
    "game.stalemateDraw": "和棋（逼和）",
    "game.drawAgreedFull": "和棋（双方同意）",
    "game.levelEasy": "简单",
    "game.levelNormal": "普通",
    "game.levelHard": "困难",
    "game.levelMaster": "大师",
    "game.levelShortEasy": "简单",
    "game.levelShortNormal": "普通",
    "game.levelShortHard": "困难",
    "game.levelShortMaster": "大师",
    "about.title": "关于",
    "about.version": "1.1",
    "about.developer": "开发者",
    "about.aboutApp": "应用说明",
    "about.aboutAppBody": "Chess 是一款运行在 Xiaomi Band Vela 上的离线西洋棋快应用，不需要网络或手机伴侣。内置 AI 引擎，可在没有第二位玩家时与电脑对弈。",
    "about.supportedRules": "已支持的规则",
    "about.supportedRulesBody": "棋子基本走法与吃子、将军、将死、逼和、王车易位、吃过路兵、兵升变、三次重复和棋、五十回合和棋。",
    "about.notSupported": "尚未完整支持",
    "about.notSupportedBody": "兵升变目前自动升为后，暂不支持选择升变为车、象或马；暂不支持棋局历史保存与 PGN 导入导出。",
    "about.pieces": "棋子素材",
    "about.piecesBody": "棋子外观来自 lichess 默认棋子集 cburnett，作者 Colin M.L. Burnett，以 CC-BY-SA-3.0 许可使用。",
    "about.afdian": "爱发电主页",
    "about.afdianBody": "这是我的爱发电主页，希望能够捐赠支持一下。",
    "about.afdianButton": "点击查看大图二维码",
    "about.thanks": "感谢你的支持",
    "about.goPay": "前往付款",
    "support.title": "爱发电主页",
    "support.hint": "扫码支持开发者",
    "support.caption": "这是我的爱发电主页",
    "support.body": "如果你喜欢这个项目，希望能够捐赠支持一下。",
    "support.backToAbout": "返回关于",
    "purchase.title": "爱发电购买",
    "purchase.price": "2元",
    "purchase.priceText": "诚信付费，希望有人购买... (-_-;)",
    "purchase.tokenText": "消耗了我1.3亿 Token（60元左右）",
    "purchase.featureText": "主要是要做想做其他功能，但是做一半又放弃了。以后看一下能不能再更新出来一些其他的功能 (@_@)",
    "purchase.projectText": "也可以看一下我另一个项目",
    "purchase.browserText": "这个呢是一个带有 AI 功能、RSS 订阅源和浏览器的软件「腕上浏览器」，希望能看看，谢谢喵～",
    "purchase.confirm": "已购买",
  },
  en: {
    "app.name": "Chess",
    "app.continueGame": "Continue game",
    "app.startGame": "Start game",
    "app.settings": "Chess settings",
    "app.about": "About",
    "app.exitApp": "Exit app",
    "app.done": "Done",
    "setup.step1Title": "Choose mode",
    "setup.step2Title": "Time",
    "setup.modeTwo": "2 Players",
    "setup.modeTwoDesc": "Two people share this band",
    "setup.modeAi": "vs AI",
    "setup.modeAiDesc": "Play the built-in engine",
    "setup.sideLabel": "I play",
    "setup.sideWhite": "White",
    "setup.sideBlack": "Black",
    "setup.minutesLabel": "Time",
    "setup.minutesUnit": "min",
    "setup.minutesInf": "No limit",
    "setup.incrementLabel": "Incr.",
    "setup.incrementUnit": "sec",
    "setup.levelLabel": "Level",
    "setup.levelEasy": "Easy",
    "setup.levelNormal": "Normal",
    "setup.levelHard": "Hard",
    "setup.levelMaster": "Master",
    "setup.levelEasyShort": "Easy",
    "setup.levelNormalShort": "Norm",
    "setup.levelHardShort": "Hard",
    "setup.levelMasterShort": "Pro",
    "setup.next": "Next",
    "setup.start": "Start",
    "settings.title": "Chess settings",
    "settings.autoCenter": "Auto-center on select",
    "settings.boardSize": "Board size",
    "settings.boardStandard": "Standard",
    "settings.boardLarge": "Large",
    "settings.boardCompact": "Compact",
    "settings.language": "Language",
    "settings.langSystem": "System",
    "settings.langChinese": "中文",
    "settings.langEnglish": "English",
    "settings.on": "On",
    "settings.off": "Off",
    "game.white": "White",
    "game.black": "Black",
    "game.undo": "Undo",
    "game.menu": "Menu",
    "game.menuTitle": "Game menu",
    "game.endGame": "End game",
    "game.resign": "Resign",
    "game.draw": "Draw",
    "game.exitGame": "Exit game",
    "game.continueGame": "Continue game",
    "game.playAgain": "Play again",
    "game.viewGame": "View game",
    "game.autoCenterOn": "Auto-center",
    "game.boardSizeLabel": "Board size",
    "game.playVsAi": "Play vs AI",
    "game.aiLevelLabel": "AI level",
    "game.hintTap": "Tap a piece to move",
    "game.gameOver": "Game over",
    "game.whiteTurn": "White's turn",
    "game.blackTurn": "Black's turn",
    "game.noUndo": "Nothing to undo",
    "game.undoDone": "Move undone",
    "game.thinking": "Thinking",
    "game.aiCantMove": "AI cannot move",
    "game.boardError": "Position error",
    "game.resignAsk": "Opponent resigned",
    "game.youWhite": "You play White",
    "game.youBlack": "You play Black",
    "game.whiteFirst": "White moves first",
    "game.drawAgreed": "By agreement",
    "game.stalemate": "stalemate",
    "game.checkmate": "checkmate",
    "game.timeout": "timeout",
    "game.wins": "wins",
    "game.settingsTitle": "Game settings",
    "game.closeSettings": "Done",
    "game.on": "On",
    "game.off": "Off",
    "game.aiTurn": "AI to move…",
    "game.aiWhiteFirst": "AI plays White first",
    "game.switchedTwo": "Switched to 2-player",
    "game.selectHint": "Select a piece of the side to move",
    "game.moveDone": "Move played, pass to ",
    "game.checkPass": "Check! Pass to ",
    "game.reselect": "Selected ",
    "game.tapBlueDot": ", tap a blue dot",
    "game.restoredTurn": "Game restored, ",
    "game.selectedTurn": "'s turn",
    "game.gameOverHint": "Game over",
    "game.drawShort": "Draw",
    "game.resignWins": " wins (resignation)",
    "game.timeoutWins": " wins (timeout)",
    "game.mateWins": " wins (checkmate)",
    "game.stalemateDraw": "Draw (stalemate)",
    "game.drawAgreedFull": "Draw (agreed)",
    "game.levelEasy": "Easy",
    "game.levelNormal": "Normal",
    "game.levelHard": "Hard",
    "game.levelMaster": "Master",
    "game.levelShortEasy": "Easy",
    "game.levelShortNormal": "Norm",
    "game.levelShortHard": "Hard",
    "game.levelShortMaster": "Pro",
    "about.title": "About",
    "about.version": "1.1",
    "about.developer": "Developer",
    "about.aboutApp": "About this app",
    "about.aboutAppBody": "Chess is an offline chess quick app for Xiaomi Band Vela. No network or phone companion is required. A built-in AI engine lets you play against the computer when no second player is available.",
    "about.supportedRules": "Supported rules",
    "about.supportedRulesBody": "Basic piece movement and captures, check, checkmate, stalemate, castling, en passant, pawn promotion, threefold repetition, and the fifty-move draw rule.",
    "about.notSupported": "Not fully supported",
    "about.notSupportedBody": "Pawn promotion currently defaults to a queen; choosing a rook, bishop, or knight is not supported. Saving game history and PGN import/export are not supported yet.",
    "about.pieces": "Piece artwork",
    "about.piecesBody": "Pieces use the cburnett set, the default on lichess.org. Art by Colin M.L. Burnett, used under CC-BY-SA-3.0.",
    "about.afdian": "Afdian page",
    "about.afdianBody": "This is my Afdian page. Donations are welcome.",
    "about.afdianButton": "Tap to view the QR code",
    "about.thanks": "Thank you for your support",
    "about.goPay": "Go to payment",
    "support.title": "Afdian page",
    "support.hint": "Scan to support the developer",
    "support.caption": "This is my Afdian page",
    "support.body": "If you enjoy this project, please consider making a donation.",
    "support.backToAbout": "Back to About",
    "purchase.title": "Support via Afdian",
    "purchase.price": "¥2",
    "purchase.priceText": "An honest ask — I hope someone buys it… (-_-;)",
    "purchase.tokenText": "Cost me 130M tokens (about ¥60)",
    "purchase.featureText": "I wanted to build more features but abandoned them halfway. Maybe some will make it in later. (@_@)",
    "purchase.projectText": "Also check out my other project",
    "purchase.browserText": "“Wrist Browser” — a watch app with AI, RSS feeds and a browser. Please take a look, thank you~",
    "purchase.confirm": "Purchased",
  }
};

/*
 * tr(key) — look up a string in the active language. Falls back to the
 * English entry, then to the key itself, so a missing key is visible
 * rather than blank.
 */
export function tr(key) {
  const row = TABLE[_lang] || TABLE.en;
  if (row && Object.prototype.hasOwnProperty.call(row, key)) return row[key];
  if (TABLE.en && Object.prototype.hasOwnProperty.call(TABLE.en, key)) return TABLE.en[key];
  return key;
}

export default { tr, setLang, setSystemLang, systemLang, getLang, getMode, resolveLang, LANG_ZH, LANG_EN };
