const fs = require('fs');
const path = require('path');
const assert = require('assert');
const root = path.resolve(__dirname, '..');
const src = path.join(root, 'src');
const read = file => fs.readFileSync(path.join(src, file), 'utf8');
const manifest = JSON.parse(read('manifest.json'));
const pages = Object.keys(manifest.router.pages).sort();
const expected = ['pages/about', 'pages/game', 'pages/index', 'pages/settings', 'pages/setup', 'pages/support'];
if (manifest.router.pages['pages/purchase']) expected.push('pages/purchase');
expected.sort();
assert.strictEqual(manifest.package, 'com.xykadi.chess');
assert.strictEqual(manifest.versionName, '1.0.0');
assert.strictEqual(manifest.versionCode, 100);
assert.deepStrictEqual(pages, expected);
assert.deepStrictEqual(manifest.deviceTypeList, ['watch']);
assert.strictEqual(manifest.simulationVersion, 'default');
assert(manifest.config && manifest.config.designWidth > 0);
for (const route of pages) {
  const component = manifest.router.pages[route].component;
  const file = `pages/${route.slice('pages/'.length)}/${component}.ux`;
  const source = read(file);
  assert(source.includes('<template>') && source.includes('<style>') && source.includes('<script>'), `${file}: incomplete UX file`);
  const match = source.match(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/i);
  assert(match, `${file}: missing script block`);
  const script = match[1].replace(/^\s*import[^\n]*\n/gm, '').replace(/export\s+default\s*\{/, 'return {');
  new Function(script);
}
const home = read('pages/index/index.ux');
assert.strictEqual((home.match(/Start game/g) || []).length, 1, 'home must expose one Start game label');
assert.strictEqual((home.match(/>New game</g) || []).length, 0, 'home must not expose duplicate New game button');
const setup = read('pages/setup/setup.ux');
assert(setup.includes('Unlimited time'));
assert(setup.includes("router.push({uri:'/pages/game'"));
assert(setup.includes("unlimited:unlimited?'true':'false"));
assert((setup.match(/@touchend=/g) || []).length >= 5);
const settings = read('pages/settings/settings.ux');
assert(settings.includes('boardSize'));
const game = read('pages/game/game.ux');
assert(game.includes("protected: { minutes: '10', unlimited: 'false', boardSize: '30', resume: 'false' }"));
assert(game.includes('CHESS_ACTIVE_GAME'));
assert(game.includes('CHESS_SETTINGS'));
assert(game.includes('newPosition()'));
assert(game.includes('getMoves('));
assert(game.includes('startClock()') && game.includes('stopClock()'));
assert(game.includes("resultTitle='Draw'"));
console.log('Current Vela source checks: PASS');
console.log(`Version: ${manifest.versionName} (${manifest.versionCode}), designWidth=${manifest.config.designWidth}`);
console.log(`Routes checked: ${pages.length}`);
